### ISSUE TITLE
Event listener/callback functionality

### ISSUE THREAD

**Issue by evanofslack** [evanofslack/pyminion#102]
It would be nice to introduce some sort of event listener / callback functionality to react to events. Cards should be able to register events to react to certain conditions, and when those conditions are met, callbacks need to fire. 

For example, Merchant needs to listen for silver to be played, Moat needs to listen for incoming attacks.

**Comment by jbw3** [comment]
@evanofslack 
I'm willing to look into this. I can create a draft PR for us to discuss

**Comment by evanofslack** [comment]
closed by @jbw3 with #104
