### ISSUE TITLE
Suggestion for Simplifying Player Decisions

### ISSUE THREAD

**Issue by jbw3** [evanofslack/pyminion#99]
I have been implementing some Intrigue cards (https://github.com/jbw3/pyminion/tree/intrigue) which require prompting the user for a lot of input. This requires the card implementations to do a lot of checking for whether the player is a human or a bot. I think that this code could be simplified if the base `Player` class had methods for getting player decisions (e.g. `single_card_decision`, `multiple_card_decision`, etc.). Then each derived class would implement those methods. The `Human` implementation would prompt the user, and `Bot` implementations would be overridden by the derived bot classes. Cards would no longer need to know what kind of player they have been passed. If you are interested, I could look into making these changes.

**Comment by evanofslack** [comment]
@jbw3 

The current implementation where each card has to handle both cases is far from ideal. I agree with your logic, this would be a welcome changes.

In my view, there should be an abstract class or protocol that defines decision interfaces, then `human` and `bot` can implement the interface as needed. In this way, cards only have to depend on the interface and not the concrete type.

Let me know if you would like to discuss further, this would be an interesting and much needed change.

**Comment by jbw3** [comment]
Great! The abstract class/protocol makes sense to me. If I get a chance over the next few days, I will start a prototype and push up a work-in-progress pull request that we can use to discuss details.
